---
sudo: false
language: C

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - brew install sdl
  - brew install std2
  - brew install sdl_net
  - brew install sdl_ttf
  - brew install sdl_image
os:
  - osx

env:
    - BUILD=native CC=clang MODE=release
    - BUILD=native CC=clang MODE=debug
    - BUILD=native CC=gcc MODE=release
    - BUILD=native CC=gcc MODE=debug

script:
  - make

branches:
  only:
    - master
