.TH BOMBERMAN 1 2016-02-12 bomberman
.SH NAME
bomberman \- run a Dyna Blaster game!
.SH SYNOPSIS
.B bomberman
\fI \fR[\fIOPTIONS\fR...]
.SH DESCRIPTION
.B bomberman
Bomberman (ボンバーマン) is a video game from 1983 developed by Hudson Soft
.SH OPTIONS
.TP
\fB\-kamikaze\f
start with kamikaze ia

.TP
\fB\-2560 -1920 -1600 -1280 -800\f
start with resolution

.TP
\fB\-arcade\f
start without exit button

.TP
\fB\-gen\f
generate the map
